[build-system]
# PEP 518: The minimum build requirement used in setup.py (before install depndencies)
requires = ["setuptools", "wheel", "pybind11>=2.6.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-ra --import-mode=importlib --ignore-glob=tutorials/*.py"
filterwarnings = [
    # By default, all warnings are treated as errors
    "error",
    # patsy is a statsmodels dependency which currently triggers a DeprecationWarning
    "default::DeprecationWarning:patsy.constraint",
    # pytorch warns about vmap usage since it's experimental
    "ignore:torch.vmap is an experimental prototype.*:UserWarning",
    # pandas sometimes complains about binary compatibility with numpy
    "default:numpy.ufunc size changed, may indicate binary incompatibility.*:RuntimeWarning",
    # flowtorch warnings
    "ignore:DenseAutoregressive input_dim = 1. Consider using an affine transformation instead.*:UserWarning"
]
